#!/bin/sh
read local_ref local_sha remote_ref remote_sha

# Check for the Python command
if command -v python3 &> /dev/null; then
    PYTHON_CMD="python3"
elif command -v python &> /dev/null; then
    PYTHON_CMD="python"
elif command -v py &> /dev/null; then
    PYTHON_CMD="py"
else
    echo "Python is not installed or not found in PATH!"
    exit 1
fi
commit_message=$(git log -1 --format=%B "$local_sha")

$PYTHON_CMD ./.git/hooks/pre-push.py "$local_sha" "$commit_message"
